import { Caveat_Brush, Chewy, Geist, Geist_Mono, Nunito_Sans, Roboto_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geistSans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geistMono",
  subsets: ["latin"],
});
const nunitoSans = Nunito_Sans({
  variable: "--font-nunitoSans",
  subsets: ["latin"],
});
const caveatBrush = Caveat_Brush({
  variable: "--font-caveatBrush",
  subsets: ["latin"],
  weight: ["400"]
 
});
const robotoMono = Roboto_Mono({
  variable: "--font-robotoMono",
  subsets: ["latin"],
  weight: ["400"]
 
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
      className={`
    ${geistSans.variable} 
    ${geistMono.variable} 
    ${nunitoSans.variable}
    ${caveatBrush.variable} 
    antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
